// ══════════════════════════════════════════════════════════════════════════════
// TRANSLATIONS
// ══════════════════════════════════════════════════════════════════════════════

let currentLang = localStorage.getItem('calc_lang') || 'ru';
let tourStep = 0;

const LANG = {
  ru:{
    headerSub:'/ калькулятор партнёра',
    tabCalc:'⚡ Калькулятор', tabCompare:'📊 RS vs CPA', tabScenarios:'⚖️ Сценарии',
    tabSubaff:'🔗 Суб-аффилейт', tabWhy:'✅ Почему lil.bet',
    scAHeader:'Сценарий A', scBHeader:'Сценарий B', scDiffHeader:'Сравнение сценариев',
    earn1m:'1 мес', earn3m:'3 мес', earn6m:'6 мес', earn12m:'12 мес',
    partnerEarn:'Партнёру', brandNgr:'NGR бренда',
    seasonNote:'⚠️ Сезонность не учтена — реальные значения могут отличаться на ±20–30% в праздники и Рамадан',
    tourSkip:'Пропустить', tourNext:'Далее →', tourFinish:'Готово!',
    tourSteps:[
      {title:'👋 Добро пожаловать!', text:'Этот калькулятор покажет реальный доход с партнёрской программы lil.bet. Займёт 30 секунд. Начнём с выбора ГЕО.'},
      {title:'🌍 Шаг 1 — Выбери ГЕО', text:'Выбери страну, в которую льёшь трафик. Каждое ГЕО имеет свои NGR-бенчмарки и лесенку RS.'},
      {title:'📡 Шаг 2 — Источник трафика', text:'Выбери откуда приходят игроки. Качество трафика влияет на NGR и итоговый доход.'},
      {title:'📊 Шаг 3 — Модель выплат', text:'RS = процент от NGR каждый месяц пока игроки активны. CPA = разово за каждый FTD. Hybrid = оба варианта.'},
      {title:'💰 Шаг 4 — Твой доход', text:'Всё посчитано! Видишь NGR бренда и выплату партнёру. Меняй ГЕО, FTD, RS — результаты обновляются в реальном времени.'},
    ],
    uspItems:[
      ['0️⃣','0% Admin fee — получаешь полный RS','Admin fee — это скрытый вычет из NGR ДО расчёта RS. Пример: Pin-Up берёт 20% → при RS 25% реально ты получаешь 25% × 0.80 = 20% NGR. У нас fee 0%: наши 25% RS — это честные 25% NGR без вычетов. Это эквивалентно 31%+ у Pin-Up.','#1'],
      ['🚫','Нет переноса отрицательного баланса (NNCO)','Плохой месяц (минусовой NGR) не вычитается из следующего. Mostbet, 1xPartners, Melbet переносят минус — у нас он сгорает в конце месяца. Начинаешь каждый месяц с нуля.','USP'],
      ['🪙','$30 с еженедельной выплатой по вторникам','Минимальный порог ниже Mostbet ($50), Pin-Up ($50), Parimatch ($100). Крипто-выплата без задержек.','🔥'],
      ['🔗','Sub-affiliate 7% — выше рынка','Рыночный диапазон: 3–10%. Mostbet даёт 2%, Pin-Up 3%. Наши 7% — одна из лучших ставок на рынке.'],
      ['🍪','Cookie 30 дней Last Win','Vavada — только сессия, Mostbet — только сессия. У нас cookie работает 30 дней.'],
      ['⚡','Прямой менеджер, живое общение','Никаких тикетов. Условия, промо, выплаты — решается в чате напрямую.'],
      ['📱','Telegram без ограничений','Каналы, боты, mini-apps, APK, PWA — всё принимаем.'],
      ['🚀','Нет FTD кэпа при тесте','Работаем на любой объём сразу — без пробных 50 FTD.'],
    ],
    // Static section labels
    geoSec:'ГЕО',
    trafficSec:'Объём трафика',
    ftdLabel:'FTD в месяц',
    clicksLabel:'Кликов в месяц',
    modeFtd:'Знаю FTD',
    modeClicks:'Знаю клики',
    roiToggle:'💰 ROI-расчёт (учесть расходы)',
    srcSec:'Источник трафика',
    modelSec:'Модель выплат',
    ngrLabel:'NGR бренда / мес',
    earnLabel:'Выплата партнёру / мес',
    timelineSec:'Доход с когорты',
    metricsSecLabel:'Метрики игрока',
    tierSec:'Лестница RevShare',
    payoutSec:'Условия выплат',
    compareSec:'Доход с одной когорты по месяцам (накопленно)',
    compareIntro:'Как работает сравнение: за каждый FTD по CPA партнёр получает фиксированную выплату один раз. По RS — процент от каждого проигрыша игрока: через неделю, через месяц, через год.',
    rollingSec:'📈 12-месячный прогноз — постоянный поток трафика',
    whyUspSec:'Ключевые преимущества',
    whyPaySec:'Условия выплат — кратко',
    whyAcceptSec:'Что принимаем',
    whyRestrictSec:'Ограничения',
    whyCompetitorSec:'lil.bet vs конкуренты — ключевые метрики',
    managerSec:'Твой менеджер в lil.bet',
    subSec:'Ваша суб-сеть',
    // Dynamic render strings
    metricsChanged:'✎ метрики изменены',
    promoNone:'Бонусов нет. GGR = NGR =',
    promoHas:'= NGR. RS считается от NGR.',
    promoGgr:'GGR', promoMinus:'− бонусы', promoLabel:'промо',
    perWeek:'/ нед.',belowThreshold:'⚠ Ниже порога $30',
    rsTimelineLabel:'RS растёт по мере возврата игроков',
    cpaTimelineLabel:'CPA — разовая выплата, не растёт',
    hybridTimelineLabel:'Hybrid: CPA разово + RS за возвраты',
    firstDeposit:'первый депозит', perPlayer:'на игрока',
    cohortLabel:'когортный', avgFtdLabel:'первый депозит',
    ngr1mShort:'NGR / 1мес', ngr6mShort:'NGR / 6мес', ltv12mShort:'LTV / 12мес',
    tierCurrentMark:'← текущий', tierMaxed:'✓ Максимальный тир достигнут',
    tierMoreFtd:'Ещё', tierFtdWord:'FTD', tierAndRate:'в этом месяце — и ставка вырастет до',
    tierOnAll:'на весь месяц',
    tierHowLabel:'Как работает лесенка:',
    tierHowText:'ставка определяется по количеству FTD <em>в текущем месяце</em> и применяется <em>ко всем FTD</em> этого месяца целиком — не к части.',
    tierMonthReset:'В следующем месяце считается заново.',
    tierBringFtd:'Приведи', tierFtdRate:'FTD → ставка',
    rsSliderLabel:'RevShare % (согласованный):',
    rsTierHigher:'📈 Тир по объёму:', rsTierApplied:'— применяется автоматически (выше согласованного)',
    rsTierLower:'Тир по объёму:', rsTierApplied2:'Применяется согласованная ставка',
    rsTierEqual:'Тир совпадает со ставкой:',
    rsSliderMin:'15% старт', rsSliderMid:'25–40% основная', rsSliderMax:'65% топы',
    cpaUnavail:'⛔ CPA недоступна для этого ГЕО',
    cpaAskManager:'Ставка CPA для', cpaAskManager2:'уточняйте у менеджера',
    cpaCustomLabel:'Ставка CPA, $',
    hybridOfficialPre:'Официальная гибридная модель:',hybridOfficialPerFtd:'/FTD разово +',hybridOfficialRs:'RS от NGR',
    hybridCpaPart:'CPA часть', hybridRsPart:'RS часть',
    hybridCpaOnce:'за каждый FTD (разово)', hybridRsMonthly:'от NGR игрока ежемесячно',
    hybridManualPre:'Ручной гибрид: CPA-выплата разово за FTD + RS от NGR каждый месяц',
    hybridCpaLabel:'CPA за каждый FTD:', hybridRsLabel:'RS от NGR:',
    hybridCpaOnceNote:'CPA выплачивается', hybridCpaOnceBold:'один раз', hybridCpaOnceEnd:'при привлечении FTD.',
    hybridRsNote:'RS начисляется', hybridRsBold:'ежемесячно', hybridRsEnd:'пока игрок активен.',
    holdDays:'Hold: 14 дней', cpaAskNote:'Ставка уточняется у менеджера. Hold: 14 дней.',
    egyptWarn:'⚠️ Бренд-трафик', egyptWarn2:'для Египта: RS применяется как 10% — ограничение программы. Используйте небрендовые ключи или другой источник.',
    // Compare tab
    rsByYear:'RS партнёру / год', cpaOncePay:'CPA партнёру разово', diffYear:'Разница за год',
    rsWins:'RS выгоднее за год', cpaWins:'CPA даёт больше — игроки не задерживаются долго',
    cmpLegendRs:'RS % (накопленно с когорты)', cmpLegendCpa:'CPA $ (одноразово)',
    beCross:'RS окупает CPA на', beMonth:'-м месяце', beAfter:'— после этого каждый месяц приносит дополнительный доход. Игрок возвращается и проигрывает снова — партнёр получает % каждый раз.',
    beWarnPre:'⚠️ При текущих параметрах CPA даёт больше за 12 месяцев. RS становится выгоднее при повышении ставки до', beWarnOr:'% или при объёме FTD от',
    cmpPeriod:'Период', rsCumulHeader:'RS (накопленно)', cpaHeader:'CPA (разово)', diffHeader:'Разница', ngrBrandHeader:'NGR бренда',
    cmpFootnote:'* RS считается от накопленного NGR когорты (игроки возвращаются, продолжают играть). CPA выплачивается один раз за FTD.',
    // RS Args
    rsArgPassive:'Пассивный доход с каждого возврата',
    rsArgPassiveDesc:'Игрок вернулся через 3 недели и проиграл снова — по CPA партнёр не получит ничего, по RS получит ещё',
    rsArgPassiveEnd:'от его проигрыша.',
    rsArgWhale:'Whale-эффект',
    rsArgWhaleDesc:'Крупный игрок с NGR $500/мес даст RS',
    rsArgWhaleEnd:'/мес. По CPA он стоил бы столько же, сколько игрок с минимальным депозитом.',
    rsArgShave:'Нет риска шейва', rsArgShaveDesc:'RS считается от реального NGR — всё видно в статистике. CPA легче занижать.',
    rsArgCumul:'Накопительный эффект',
    rsArgCumulDescPre:'При стабильном трафике база игроков растёт. К 12-му месяцу',
    rsArgCumulDescMid:'FTD ежемесячно дают накопленный пул ~', rsArgCumulEnd:'активных игроков.',
    rsArgCpa:'CPA лучше при коротком горизонте', rsArgCpaDesc:'Если партнёр планирует работать 1–3 месяца — CPA выгоднее. RS раскрывается на 6–12+ месяцах.',
    // SubAff
    ftdNetLabel:'FTD всей сети / мес', myMonthLabel:'Ваш доход / мес', myYearLabel:'Ваш доход / год',
    partnersHeader:'Партнёров', ngrNetHeader:'NGR сети / мес',
    subTipsItems:[
      ['🎯','Качество > количество','Один партнёр с 200 FTD выгоднее десяти с 20. Фокусируйся на командах и медиабайерах.'],
      ['📊','Показывай этот калькулятор','Партнёр видит реальные цифры — не проценты, а деньги. Это ускоряет принятие решения.'],
      ['🔗','Суб-аффилейт как якорь','Партнёр, строящий свою сеть через тебя, не уйдёт — у него двойная мотивация оставаться.'],
      ['📈','Рост ставки как стимул','Предлагай повышение RS при масштабировании: 25% → 30% → 35%. Стимул лить больше.'],
    ],
    // ROI
    adBudgetLabel:'Рекламный бюджет', partnerMonthLabel:'Доход партнёра / мес',
    netProfitLabel:'Чистая прибыль', roiLabel:'ROI',
    costPerFtdLabel:'Стоимость 1 FTD', paybackLabel:'Окупаемость бюджета',
    profitable:'✅ Кампания прибыльная. На каждый $1 расходов — $', profitableEnd:'дохода.',
    unprofitable:'⚠️ Убыток при текущих параметрах. Попробуй снизить CPC, повысить конверсию или объём.',
    moSuffix:'мес', moSuffixGt:'> 24 мес',
    // Rolling
    rollingDescPre:'Вы стабильно приводите', rollingDescMid:'FTD каждый месяц',
    rollingDescPost:'Игроки предыдущих месяцев возвращаются и продолжают играть — RS-доход', rollingDescGrow:'растёт каждый месяц',
    rollingDescEnd:' даже если объём трафика не меняется. CPA — фиксирован: сколько новых FTD, столько и заплатят.',
    rollingLegendRsSuffix:'% / мес (доход за месяц)', rollingLegendCpaSuffix:'/ мес (новые FTD × ставка)',
    rollMo1:'RS в мес. 1', rollMo6:'RS в мес. 6', rollMo12:'RS в мес. 12',
    rollGrowth:'Рост ×', rollMo1Sub:'только новые игроки', rollMo6Sub:'6 когорт работают', rollMo12Sub:'12 когорт работают', rollGrowthSub:'мес 1 → мес 12',
    rollRs12:'RS за 12 мес (суммарно)', rollCpa12:'CPA за 12 мес (суммарно)',
    rollCrossPre:'📈 С', rollCrossMid:'-го месяца ежемесячный RS-доход превышает CPA-выплату. К 12-му месяцу RS приносит',
    rollCrossMonEnd:'/мес — в', rollCrossX:'× больше, чем CPA за тот же месяц.',
    rollNoCross:'RS растёт, но при текущих параметрах CPA остаётся выгоднее помесячно. Попробуйте повысить RS ставку или выбрать ГЕО с высоким LTV.',
    // Why
    acceptSrcItems:[
      '✅ SEO / Контент','✅ Telegram (каналы, боты, mini-apps)','✅ Facebook / Instagram (PWA, APK)',
      '✅ Google UAC / ASO','✅ TikTok / Reels','✅ Инфлюенсеры / Стримеры',
      '✅ Push / Native','✅ Email / SMS','✅ Арбитраж любого типа',
      '✅ Любой источник, который приводит реальных игроков',
    ],
    acceptSrcNote:'💬 Работаешь с нестандартным источником? Напиши менеджеру — найдём решение.',
    restrictItems:[
      '⛔ Брендовый PPC (контекст по ключу lil.bet)',
      '⛔ Cookie stuffing','⛔ Спам-рассылки',
      '⛔ Клоакинг / маскировка трафика','⛔ Сайты-имитаторы бренда',
      '⛔ Египет: SEO/ASO/Google по бренду → RS 10%',
      '⛔ USA, UK, France, Spain, Ukraine — блок',
    ],
    competitorHeaders:['Партнёрка','RS диапазон','Admin fee','Отриц. баланс','Sub-aff','Мин. выплата','Cookie'],
    competitorNote:'Данные — публичные условия партнёрских программ на май 2026. Admin fee снимается с NGR до расчёта RS: при fee 20% и RS 25% реальная ставка = 25% × 0.8 = 20% эффективно.',
    // Scenario
    scPeriod:'Период', scDiff:'Разница',
    scApproxEqual:'≈ равно', scWinA:'▲ A +', scWinB:'▲ B +',
    scInsightWin:'Сценарий', scInsightWinMid:'выгоднее за 12 мес на', scInsightWinEnd:'показывает лучший LTV при данных параметрах.',
    scInsightEqual:'⚖️ Сценарии примерно равны по доходности за 12 месяцев. Попробуй изменить ГЕО или модель.',
    sc1mLabel:'1 мес', sc3mLabel:'3 мес', sc6mLabel:'6 мес', sc12mLabel:'12 мес',
    scMoSuffix:'1 мес',
    // Payout section
    payMin:'Мин. выплата:', payFreq:'Периодичность:', payMethod:'Метод:', payHold:'Hold (CPA):',
    payMinVal:'$30', payFreqVal:'Еженедельно (вторник)', payMethodVal:'Крипто (USDT, BTC, ETH)', payHoldVal:'14 дней',
  },
  en:{
    headerSub:'/ partner calculator',
    tabCalc:'⚡ Calculator', tabCompare:'📊 RS vs CPA', tabScenarios:'⚖️ Scenarios',
    tabSubaff:'🔗 Sub-affiliate', tabWhy:'✅ Why lil.bet',
    scAHeader:'Scenario A', scBHeader:'Scenario B', scDiffHeader:'Scenario comparison',
    earn1m:'1 mo', earn3m:'3 mo', earn6m:'6 mo', earn12m:'12 mo',
    partnerEarn:'Partner', brandNgr:'Brand NGR',
    seasonNote:'⚠️ Seasonality not included — real values may vary ±20–30% during holidays and Ramadan',
    tourSkip:'Skip', tourNext:'Next →', tourFinish:'Done!',
    tourSteps:[
      {title:'👋 Welcome!', text:'This calculator shows real earnings from the lil.bet affiliate program. Takes 30 seconds. Let\'s start with GEO selection.'},
      {title:'🌍 Step 1 — Choose GEO', text:'Pick the country you send traffic to. Each GEO has its own NGR benchmarks and RS ladder.'},
      {title:'📡 Step 2 — Traffic source', text:'Choose where players come from. Traffic quality affects NGR and total earnings.'},
      {title:'📊 Step 3 — Payout model', text:'RS = % of NGR monthly while players are active. CPA = one-time per FTD. Hybrid = both.'},
      {title:'💰 Step 4 — Your earnings', text:'All calculated! See brand NGR and partner payout. Change GEO, FTD, RS — results update in real time.'},
    ],
    uspItems:[
      ['0️⃣','0% Admin Fee — you keep the full RS','Admin fee is a hidden deduction from NGR BEFORE RS is calculated. Example: Pin-Up takes 20% → at RS 25% you actually get 25% × 0.80 = 20% of NGR. Our fee is 0%: our 25% RS is an honest 25% of NGR. Equivalent to 31%+ at Pin-Up.','#1'],
      ['🚫','No Negative Carryover (NNCO)','A losing month doesn\'t roll into the next. Mostbet, 1xPartners, Melbet carry the negative forward — ours resets to zero every month.','USP'],
      ['🪙','$30 weekly payouts every Tuesday','Lower threshold than Mostbet ($50), Pin-Up ($50), Parimatch ($100). Crypto payout, no delays.','🔥'],
      ['🔗','Sub-affiliate 7% — above market','Market range: 3–10%. Mostbet pays 2%, Pin-Up 3%. Our 7% is one of the best rates on the market.'],
      ['🍪','30-day Last Win cookie','Vavada is session-only, Mostbet is session-only. Our cookie runs 30 days.'],
      ['⚡','Direct manager, live chat','No tickets. Conditions, promos, payouts — resolved in chat directly.'],
      ['📱','Telegram-friendly','Channels, bots, mini-apps, APK, PWA — all accepted.'],
      ['🚀','No FTD cap on test','Work at any volume immediately — no trial 50 FTD period.'],
    ],
    geoSec:'GEO',
    trafficSec:'Traffic volume',
    ftdLabel:'FTD per month',
    clicksLabel:'Clicks per month',
    modeFtd:'I know FTD',
    modeClicks:'I know clicks',
    roiToggle:'💰 ROI Calculator (include costs)',
    srcSec:'Traffic source',
    modelSec:'Payout model',
    ngrLabel:'Brand NGR / mo',
    earnLabel:'Partner payout / mo',
    timelineSec:'Cohort income',
    metricsSecLabel:'Player metrics',
    tierSec:'RevShare ladder',
    payoutSec:'Payout terms',
    compareSec:'Cohort income by month (cumulative)',
    compareIntro:'How comparison works: for each FTD via CPA the partner receives a fixed one-time payout. Via RS — a percentage of every player loss: weekly, monthly, yearly.',
    rollingSec:'📈 12-month forecast — steady traffic flow',
    whyUspSec:'Key advantages',
    whyPaySec:'Payout terms — brief',
    whyAcceptSec:'What we accept',
    whyRestrictSec:'Restrictions',
    whyCompetitorSec:'lil.bet vs competitors — key metrics',
    managerSec:'Your lil.bet manager',
    subSec:'Your sub-network',
    metricsChanged:'✎ metrics edited',
    promoNone:'No bonuses. GGR = NGR =',
    promoHas:'= NGR. RS is calculated from NGR.',
    promoGgr:'GGR', promoMinus:'− bonuses', promoLabel:'promo',
    perWeek:'/ wk.',belowThreshold:'⚠ Below $30 threshold',
    rsTimelineLabel:'RS grows as players return',
    cpaTimelineLabel:'CPA — one-time payout, doesn\'t grow',
    hybridTimelineLabel:'Hybrid: one-time CPA + RS on returns',
    firstDeposit:'first deposit', perPlayer:'per player',
    cohortLabel:'cohort', avgFtdLabel:'first deposit',
    ngr1mShort:'NGR / 1mo', ngr6mShort:'NGR / 6mo', ltv12mShort:'LTV / 12mo',
    tierCurrentMark:'← current', tierMaxed:'✓ Maximum tier reached',
    tierMoreFtd:'More', tierFtdWord:'FTD', tierAndRate:'this month — and rate grows to',
    tierOnAll:'for the whole month',
    tierHowLabel:'How the ladder works:',
    tierHowText:'The rate is determined by the number of FTD <em>in the current month</em> and applied <em>to all FTD</em> of that month — not just part of it.',
    tierMonthReset:'Recalculated every month.',
    tierBringFtd:'Bring', tierFtdRate:'FTD → rate',
    rsSliderLabel:'RevShare % (agreed):',
    rsTierHigher:'📈 Volume tier:', rsTierApplied:'— applied automatically (above agreed)',
    rsTierLower:'Volume tier:', rsTierApplied2:'Agreed rate applied',
    rsTierEqual:'Tier matches rate:',
    rsSliderMin:'15% start', rsSliderMid:'25–40% main', rsSliderMax:'65% top',
    cpaUnavail:'⛔ CPA not available for this GEO',
    cpaAskManager:'CPA rate for', cpaAskManager2:'ask your manager',
    cpaCustomLabel:'CPA rate, $',
    hybridOfficialPre:'Official hybrid model:',hybridOfficialPerFtd:'/FTD one-time +',hybridOfficialRs:'RS of NGR',
    hybridCpaPart:'CPA part', hybridRsPart:'RS part',
    hybridCpaOnce:'per FTD (one-time)', hybridRsMonthly:'of player NGR monthly',
    hybridManualPre:'Manual hybrid: one-time CPA per FTD + RS from NGR monthly',
    hybridCpaLabel:'CPA per FTD:', hybridRsLabel:'RS of NGR:',
    hybridCpaOnceNote:'CPA is paid', hybridCpaOnceBold:'once', hybridCpaOnceEnd:'on FTD.',
    hybridRsNote:'RS is accrued', hybridRsBold:'monthly', hybridRsEnd:'while the player is active.',
    holdDays:'Hold: 14 days', cpaAskNote:'CPA rate is set by manager. Hold: 14 days.',
    egyptWarn:'⚠️ Brand traffic', egyptWarn2:'for Egypt: RS applied as 10% — program restriction. Use non-brand keywords or another source.',
    rsByYear:'RS to partner / year', cpaOncePay:'CPA to partner (one-time)', diffYear:'Difference per year',
    rsWins:'RS better for the year', cpaWins:'CPA pays more — players don\'t stay long',
    cmpLegendRs:'RS % (cumulative from cohort)', cmpLegendCpa:'CPA $ (one-time)',
    beCross:'RS recovers CPA at month', beMonth:'', beAfter:'— after that each month brings additional income. The player returns and loses again — partner gets % every time.',
    beWarnPre:'⚠️ At current parameters CPA pays more over 12 months. RS becomes better at rates above', beWarnOr:'% or FTD volume from',
    cmpPeriod:'Period', rsCumulHeader:'RS (cumulative)', cpaHeader:'CPA (one-time)', diffHeader:'Difference', ngrBrandHeader:'Brand NGR',
    cmpFootnote:'* RS is calculated from the cohort\'s cumulative NGR (players return and keep playing). CPA is paid once per FTD.',
    rsArgPassive:'Passive income on every return',
    rsArgPassiveDesc:'Player returned after 3 weeks and lost again — CPA pays nothing, RS pays another',
    rsArgPassiveEnd:'of their loss.',
    rsArgWhale:'Whale effect',
    rsArgWhaleDesc:'A high-value player with $500/mo NGR gives RS',
    rsArgWhaleEnd:'/mo. Via CPA they\'d be worth the same as a minimum-deposit player.',
    rsArgShave:'No shave risk', rsArgShaveDesc:'RS is calculated from real NGR — everything visible in stats. CPA is easier to shave.',
    rsArgCumul:'Cumulative effect',
    rsArgCumulDescPre:'With steady traffic the player base grows. By month 12,',
    rsArgCumulDescMid:'FTD/mo build a pool of ~', rsArgCumulEnd:'active players.',
    rsArgCpa:'CPA better short-term', rsArgCpaDesc:'If partner plans to work 1–3 months — CPA is better. RS shines at 6–12+ months.',
    ftdNetLabel:'Total network FTD / mo', myMonthLabel:'Your income / mo', myYearLabel:'Your income / year',
    partnersHeader:'Partners', ngrNetHeader:'Network NGR / mo',
    subTipsItems:[
      ['🎯','Quality over quantity','One partner with 200 FTD beats ten with 20. Focus on teams and media buyers.'],
      ['📊','Show this calculator','Partners see real numbers — not percentages, but money. It speeds up decisions.'],
      ['🔗','Sub-affiliate as an anchor','A partner building their own network through you won\'t leave — double incentive to stay.'],
      ['📈','Rate increase as incentive','Offer RS increases when scaling: 25% → 30% → 35%. Incentive to send more.'],
    ],
    adBudgetLabel:'Ad budget', partnerMonthLabel:'Partner income / mo',
    netProfitLabel:'Net profit', roiLabel:'ROI',
    costPerFtdLabel:'Cost per FTD', paybackLabel:'Budget payback',
    profitable:'✅ Campaign is profitable. For every $1 spent — $', profitableEnd:'earned.',
    unprofitable:'⚠️ Loss at current parameters. Try lowering CPC, improving conversion or volume.',
    moSuffix:'mo', moSuffixGt:'> 24 mo',
    rollingDescPre:'You steadily bring', rollingDescMid:'FTD every month',
    rollingDescPost:'Players from previous months return and keep playing — RS income', rollingDescGrow:'grows every month',
    rollingDescEnd:' even if traffic volume doesn\'t change. CPA is fixed: as many new FTD, as much they pay.',
    rollingLegendRsSuffix:'% / mo (monthly income)', rollingLegendCpaSuffix:'/ mo (new FTD × rate)',
    rollMo1:'RS month 1', rollMo6:'RS month 6', rollMo12:'RS month 12',
    rollGrowth:'Growth ×', rollMo1Sub:'new players only', rollMo6Sub:'6 cohorts active', rollMo12Sub:'12 cohorts active', rollGrowthSub:'month 1 → month 12',
    rollRs12:'RS total 12 mo', rollCpa12:'CPA total 12 mo',
    rollCrossPre:'📈 From month', rollCrossMid:'monthly RS income exceeds CPA payout. By month 12 RS brings',
    rollCrossMonEnd:'/mo —', rollCrossX:'× more than CPA for the same month.',
    rollNoCross:'RS grows, but at current parameters CPA stays higher monthly. Try raising RS rate or choosing a high-LTV GEO.',
    acceptSrcItems:[
      '✅ SEO / Content','✅ Telegram (channels, bots, mini-apps)','✅ Facebook / Instagram (PWA, APK)',
      '✅ Google UAC / ASO','✅ TikTok / Reels','✅ Influencers / Streamers',
      '✅ Push / Native','✅ Email / SMS','✅ Any arbitrage type',
      '✅ Any source bringing real players',
    ],
    acceptSrcNote:'💬 Using a non-standard source? Message the manager — we\'ll find a solution.',
    restrictItems:[
      '⛔ Brand PPC (search ads on lil.bet keyword)',
      '⛔ Cookie stuffing','⛔ Spam mailings',
      '⛔ Cloaking / traffic masking','⛔ Brand impersonation sites',
      '⛔ Egypt: SEO/ASO/Google on brand → RS 10%',
      '⛔ USA, UK, France, Spain, Ukraine — blocked',
    ],
    competitorHeaders:['Program','RS range','Admin fee','Neg. carryover','Sub-aff','Min payout','Cookie'],
    competitorNote:'Data — public affiliate program terms as of May 2026. Admin fee is deducted from NGR before RS: at fee 20% and RS 25% effective rate = 25% × 0.8 = 20%.',
    scPeriod:'Period', scDiff:'Difference',
    scApproxEqual:'≈ equal', scWinA:'▲ A +', scWinB:'▲ B +',
    scInsightWin:'Scenario', scInsightWinMid:'is better over 12 mo by', scInsightWinEnd:'shows best LTV at these parameters.',
    scInsightEqual:'⚖️ Scenarios are roughly equal in 12-month earnings. Try changing GEO or model.',
    sc1mLabel:'1 mo', sc3mLabel:'3 mo', sc6mLabel:'6 mo', sc12mLabel:'12 mo',
    scMoSuffix:'1 mo',
    payMin:'Min payout:', payFreq:'Frequency:', payMethod:'Method:', payHold:'Hold (CPA):',
    payMinVal:'$30', payFreqVal:'Weekly (Tuesday)', payMethodVal:'Crypto (USDT, BTC, ETH)', payHoldVal:'14 days',
  },
  uk:{
    headerSub:'/ калькулятор партнера',
    tabCalc:'⚡ Калькулятор', tabCompare:'📊 RS vs CPA', tabScenarios:'⚖️ Сценарії',
    tabSubaff:'🔗 Суб-афіліат', tabWhy:'✅ Чому lil.bet',
    scAHeader:'Сценарій A', scBHeader:'Сценарій B', scDiffHeader:'Порівняння сценаріїв',
    earn1m:'1 міс', earn3m:'3 міс', earn6m:'6 міс', earn12m:'12 міс',
    partnerEarn:'Партнеру', brandNgr:'NGR бренду',
    seasonNote:'⚠️ Сезонність не врахована — реальні значення можуть відрізнятися на ±20–30%',
    tourSkip:'Пропустити', tourNext:'Далі →', tourFinish:'Готово!',
    tourSteps:[
      {title:'👋 Ласкаво просимо!', text:'Цей калькулятор покаже реальний дохід з партнерської програми lil.bet.'},
      {title:'🌍 Крок 1 — Вибери ГЕО', text:'Вибери країну, на яку льєш трафік.'},
      {title:'📡 Крок 2 — Джерело трафіку', text:'Вибери звідки приходять гравці.'},
      {title:'📊 Крок 3 — Модель виплат', text:'RS, CPA або Hybrid — обери свою модель.'},
      {title:'💰 Крок 4 — Твій дохід', text:'Все пораховано! Змінюй параметри — результати оновлюються.'},
    ],
    uspItems:[
      ['0️⃣','0% Admin fee','Pin-Up бере 20%, Vavada 14%. Наш admin fee 0%.','#1'],
      ['🚫','Без перенесення від\'ємного балансу','Поганий місяць не переноситься.','USP'],
      ['🪙','$30 щотижня по вівторках','Крипто-виплата без затримок.','🔥'],
      ['🔗','Sub-affiliate 7%','Ринковий діапазон: 3–10%.'],
      ['🍪','Cookie 30 днів Last Win','Vavada та Mostbet — лише сесія.'],
      ['⚡','Прямий менеджер','Без тікетів.'],
      ['📱','Telegram без обмежень','Канали, боти, APK, PWA.'],
      ['🚀','Без кепу FTD','Будь-який обсяг одразу.'],
    ],
    geoSec:'ГЕО',
    trafficSec:'Обсяг трафіку',
    ftdLabel:'FTD на місяць',
    clicksLabel:'Кліків на місяць',
    modeFtd:'Знаю FTD',
    modeClicks:'Знаю кліки',
    roiToggle:'💰 ROI-розрахунок (врахувати витрати)',
    srcSec:'Джерело трафіку',
    modelSec:'Модель виплат',
    ngrLabel:'NGR бренду / міс',
    earnLabel:'Виплата партнеру / міс',
    timelineSec:'Дохід з когорти',
    metricsSecLabel:'Метрики гравця',
    tierSec:'Сходинки RevShare',
    payoutSec:'Умови виплат',
    compareSec:'Дохід з однієї когорти по місяцях (накопичено)',
    compareIntro:'Як працює порівняння: за кожен FTD по CPA партнер отримує фіксовану виплату один раз. По RS — відсоток від кожного програшу гравця.',
    rollingSec:'📈 12-місячний прогноз — постійний потік трафіку',
    whyUspSec:'Ключові переваги',
    whyPaySec:'Умови виплат — коротко',
    whyAcceptSec:'Що приймаємо',
    whyRestrictSec:'Обмеження',
    whyCompetitorSec:'lil.bet vs конкуренти — ключові метрики',
    managerSec:'Твій менеджер у lil.bet',
    subSec:'Ваша суб-мережа',
    metricsChanged:'✎ метрики змінено',
    promoNone:'Бонусів немає. GGR = NGR =',
    promoHas:'= NGR. RS рахується від NGR.',
    promoGgr:'GGR', promoMinus:'− бонуси', promoLabel:'промо',
    perWeek:'/ тиж.',belowThreshold:'⚠ Нижче порогу $30',
    rsTimelineLabel:'RS зростає по мірі повернення гравців',
    cpaTimelineLabel:'CPA — разова виплата, не зростає',
    hybridTimelineLabel:'Hybrid: CPA разово + RS за повернення',
    firstDeposit:'перший депозит', perPlayer:'на гравця',
    cohortLabel:'когортний', avgFtdLabel:'перший депозит',
    ngr1mShort:'NGR / 1міс', ngr6mShort:'NGR / 6міс', ltv12mShort:'LTV / 12міс',
    tierCurrentMark:'← поточний', tierMaxed:'✓ Максимальний тір досягнуто',
    tierMoreFtd:'Ще', tierFtdWord:'FTD', tierAndRate:'цього місяця — і ставка виросте до',
    tierOnAll:'на весь місяць',
    tierHowLabel:'Як працює сходинка:',
    tierHowText:'ставка визначається за кількістю FTD <em>у поточному місяці</em> і застосовується <em>до всіх FTD</em> цього місяця.',
    tierMonthReset:'Наступного місяця рахується заново.',
    tierBringFtd:'Приведи', tierFtdRate:'FTD → ставка',
    rsSliderLabel:'RevShare % (узгоджений):',
    rsTierHigher:'📈 Тір за обсягом:', rsTierApplied:'— застосовується автоматично',
    rsTierLower:'Тір за обсягом:', rsTierApplied2:'Застосовується узгоджена ставка',
    rsTierEqual:'Тір співпадає зі ставкою:',
    rsSliderMin:'15% старт', rsSliderMid:'25–40% основна', rsSliderMax:'65% топи',
    cpaUnavail:'⛔ CPA недоступна для цього ГЕО',
    cpaAskManager:'Ставка CPA для', cpaAskManager2:'уточнюйте у менеджера',
    cpaCustomLabel:'Ставка CPA, $',
    hybridOfficialPre:'Офіційна гібридна модель:',hybridOfficialPerFtd:'/FTD разово +',hybridOfficialRs:'RS від NGR',
    hybridCpaPart:'CPA частина', hybridRsPart:'RS частина',
    hybridCpaOnce:'за кожен FTD (разово)', hybridRsMonthly:'від NGR гравця щомісяця',
    hybridManualPre:'Ручний гібрид: CPA-виплата разово за FTD + RS від NGR щомісяця',
    hybridCpaLabel:'CPA за кожен FTD:', hybridRsLabel:'RS від NGR:',
    hybridCpaOnceNote:'CPA виплачується', hybridCpaOnceBold:'один раз', hybridCpaOnceEnd:'при залученні FTD.',
    hybridRsNote:'RS нараховується', hybridRsBold:'щомісяця', hybridRsEnd:'поки гравець активний.',
    holdDays:'Hold: 14 днів', cpaAskNote:'Ставка уточнюється у менеджера. Hold: 14 днів.',
    egyptWarn:'⚠️ Бренд-трафік', egyptWarn2:'для Єгипту: RS застосовується як 10%.',
    rsByYear:'RS партнеру / рік', cpaOncePay:'CPA партнеру разово', diffYear:'Різниця за рік',
    rsWins:'RS вигідніше за рік', cpaWins:'CPA дає більше — гравці не затримуються',
    cmpLegendRs:'RS % (накопичено з когорти)', cmpLegendCpa:'CPA $ (одноразово)',
    beCross:'RS окупає CPA на', beMonth:'-му місяці', beAfter:'— після цього кожен місяць приносить додатковий дохід.',
    beWarnPre:'⚠️ При поточних параметрах CPA дає більше за 12 місяців. RS стає вигіднішим при ставці понад', beWarnOr:'% або FTD від',
    cmpPeriod:'Період', rsCumulHeader:'RS (накопичено)', cpaHeader:'CPA (разово)', diffHeader:'Різниця', ngrBrandHeader:'NGR бренду',
    cmpFootnote:'* RS рахується від накопиченого NGR когорти. CPA виплачується один раз за FTD.',
    rsArgPassive:'Пасивний дохід з кожного повернення',
    rsArgPassiveDesc:'Гравець повернувся через 3 тижні і програв знову — по CPA партнер не отримає нічого, по RS отримає ще',
    rsArgPassiveEnd:'від його програшу.',
    rsArgWhale:'Whale-ефект',
    rsArgWhaleDesc:'Великий гравець з NGR $500/міс дасть RS',
    rsArgWhaleEnd:'/міс.',
    rsArgShave:'Немає ризику шейву', rsArgShaveDesc:'RS рахується від реального NGR. CPA легше занижувати.',
    rsArgCumul:'Накопичувальний ефект',
    rsArgCumulDescPre:'При стабільному трафіку база гравців зростає. До 12-го місяця',
    rsArgCumulDescMid:'FTD щомісяця дають накопичений пул ~', rsArgCumulEnd:'активних гравців.',
    rsArgCpa:'CPA краще при короткому горизонті', rsArgCpaDesc:'Якщо партнер планує 1–3 місяці — CPA вигідніше. RS розкривається на 6–12+ місяцях.',
    ftdNetLabel:'FTD всієї мережі / міс', myMonthLabel:'Ваш дохід / міс', myYearLabel:'Ваш дохід / рік',
    partnersHeader:'Партнерів', ngrNetHeader:'NGR мережі / міс',
    subTipsItems:[
      ['🎯','Якість > кількість','Один партнер з 200 FTD вигідніше десяти з 20.'],
      ['📊','Показуй цей калькулятор','Партнер бачить реальні цифри — не відсотки, а гроші.'],
      ['🔗','Суб-афіліат як якір','Партнер, що будує свою мережу через тебе, не піде.'],
      ['📈','Зростання ставки як стимул','Пропонуй підвищення RS: 25% → 30% → 35%.'],
    ],
    adBudgetLabel:'Рекламний бюджет', partnerMonthLabel:'Дохід партнера / міс',
    netProfitLabel:'Чистий прибуток', roiLabel:'ROI',
    costPerFtdLabel:'Вартість 1 FTD', paybackLabel:'Окупність бюджету',
    profitable:'✅ Кампанія прибуткова. На кожен $1 витрат — $', profitableEnd:'доходу.',
    unprofitable:'⚠️ Збиток при поточних параметрах.',
    moSuffix:'міс', moSuffixGt:'> 24 міс',
    rollingDescPre:'Ви стабільно приводите', rollingDescMid:'FTD кожен місяць',
    rollingDescPost:'Гравці попередніх місяців повертаються — RS-дохід', rollingDescGrow:'зростає кожен місяць',
    rollingDescEnd:' навіть якщо обсяг трафіку не змінюється.',
    rollingLegendRsSuffix:'% / міс (дохід за місяць)', rollingLegendCpaSuffix:'/ міс (нові FTD × ставка)',
    rollMo1:'RS у міс. 1', rollMo6:'RS у міс. 6', rollMo12:'RS у міс. 12',
    rollGrowth:'Зростання ×', rollMo1Sub:'лише нові гравці', rollMo6Sub:'6 когорт активні', rollMo12Sub:'12 когорт активні', rollGrowthSub:'міс 1 → міс 12',
    rollRs12:'RS за 12 міс (разом)', rollCpa12:'CPA за 12 міс (разом)',
    rollCrossPre:'📈 З', rollCrossMid:'-го місяця щомісячний RS-дохід перевищує CPA. До 12-го місяця RS приносить',
    rollCrossMonEnd:'/міс — у', rollCrossX:'× більше, ніж CPA за той самий місяць.',
    rollNoCross:'RS зростає, але CPA залишається вигіднішим помісячно. Спробуй підвищити ставку RS.',
    acceptSrcItems:[
      '✅ SEO / Контент','✅ Telegram (канали, боти, mini-apps)','✅ Facebook / Instagram (PWA, APK)',
      '✅ Google UAC / ASO','✅ TikTok / Reels','✅ Інфлюенсери / Стримери',
      '✅ Push / Native','✅ Email / SMS','✅ Будь-який арбітраж',
      '✅ Будь-яке джерело реальних гравців',
    ],
    acceptSrcNote:'💬 Працюєш з нестандартним джерелом? Напиши менеджеру — знайдемо рішення.',
    restrictItems:[
      '⛔ Брендовий PPC','⛔ Cookie stuffing','⛔ Спам-розсилки',
      '⛔ Клоакінг / маскування трафіку','⛔ Сайти-імітатори бренду',
      '⛔ Єгипет: SEO/ASO/Google по бренду → RS 10%',
      '⛔ USA, UK, France, Spain, Ukraine — блок',
    ],
    competitorHeaders:['Партнерка','RS діапазон','Admin fee','Від\'ємний баланс','Sub-aff','Мін. виплата','Cookie'],
    competitorNote:'Дані — публічні умови партнерських програм на травень 2026.',
    scPeriod:'Період', scDiff:'Різниця',
    scApproxEqual:'≈ рівно', scWinA:'▲ A +', scWinB:'▲ B +',
    scInsightWin:'Сценарій', scInsightWinMid:'вигідніше за 12 міс на', scInsightWinEnd:'показує кращий LTV.',
    scInsightEqual:'⚖️ Сценарії приблизно рівні. Спробуй змінити ГЕО або модель.',
    sc1mLabel:'1 міс', sc3mLabel:'3 міс', sc6mLabel:'6 міс', sc12mLabel:'12 міс', scMoSuffix:'1 міс',
    payMin:'Мін. виплата:', payFreq:'Періодичність:', payMethod:'Метод:', payHold:'Hold (CPA):',
    payMinVal:'$30', payFreqVal:'Щотижня (вівторок)', payMethodVal:'Крипто (USDT, BTC, ETH)', payHoldVal:'14 днів',
  },
  de:{
    headerSub:'/ Partner-Rechner',
    tabCalc:'⚡ Rechner', tabCompare:'📊 RS vs CPA', tabScenarios:'⚖️ Szenarien',
    tabSubaff:'🔗 Sub-Affiliate', tabWhy:'✅ Warum lil.bet',
    scAHeader:'Szenario A', scBHeader:'Szenario B', scDiffHeader:'Szenariovergleich',
    earn1m:'1 Mo', earn3m:'3 Mo', earn6m:'6 Mo', earn12m:'12 Mo',
    partnerEarn:'Partner', brandNgr:'Brand NGR',
    seasonNote:'⚠️ Saisonalität nicht berücksichtigt — reale Werte können ±20–30% abweichen',
    tourSkip:'Überspringen', tourNext:'Weiter →', tourFinish:'Fertig!',
    tourSteps:[
      {title:'👋 Willkommen!', text:'Dieser Rechner zeigt echte Einnahmen aus dem lil.bet Partnerprogramm.'},
      {title:'🌍 Schritt 1 — GEO wählen', text:'Wähle das Land, in das du Traffic sendest.'},
      {title:'📡 Schritt 2 — Traffic-Quelle', text:'Wähle, woher die Spieler kommen.'},
      {title:'📊 Schritt 3 — Auszahlungsmodell', text:'RS, CPA oder Hybrid.'},
      {title:'💰 Schritt 4 — Deine Einnahmen', text:'Alles berechnet! Ändere Parameter — Ergebnisse aktualisieren sich.'},
    ],
    uspItems:[
      ['0️⃣','0% Admin Fee','Pin-Up 20%, Vavada 14%. Unsere Admin Fee: 0%.','#1'],
      ['🚫','Kein negativer Übertrag','Schlechter Monat wird nicht übertragen.','USP'],
      ['🪙','$30 wöchentlich jeden Dienstag','Niedriger als Mostbet ($50), Parimatch ($100).','🔥'],
      ['🔗','Sub-Affiliate 7%','Marktbereich: 3–10%.'],
      ['🍪','Cookie 30 Tage Last Win','Vavada und Mostbet nur Session.'],
      ['⚡','Direkter Manager','Keine Tickets.'],
      ['📱','Telegram-freundlich','Alle Quellen akzeptiert.'],
      ['🚀','Kein FTD-Cap','Sofort auf jedem Volumen.'],
    ],
    geoSec:'GEO',
    trafficSec:'Traffic-Volumen',
    ftdLabel:'FTD pro Monat',
    clicksLabel:'Klicks pro Monat',
    modeFtd:'Ich kenne FTD',
    modeClicks:'Ich kenne Klicks',
    roiToggle:'💰 ROI-Rechner (Kosten einbeziehen)',
    srcSec:'Traffic-Quelle',
    modelSec:'Auszahlungsmodell',
    ngrLabel:'Brand NGR / Mo',
    earnLabel:'Partner-Auszahlung / Mo',
    timelineSec:'Kohorten-Einkommen',
    metricsSecLabel:'Spieler-Metriken',
    tierSec:'RevShare-Leiter',
    payoutSec:'Auszahlungsbedingungen',
    compareSec:'Kohorteneinkommen nach Monat (kumulativ)',
    compareIntro:'So funktioniert der Vergleich: Für jedes FTD über CPA erhält der Partner eine einmalige Zahlung. Über RS — einen Prozentsatz jedes Spielerverlusts.',
    rollingSec:'📈 12-Monats-Prognose — stetiger Traffic-Fluss',
    whyUspSec:'Wichtigste Vorteile',
    whyPaySec:'Auszahlungsbedingungen — kurz',
    whyAcceptSec:'Was wir akzeptieren',
    whyRestrictSec:'Einschränkungen',
    whyCompetitorSec:'lil.bet vs Konkurrenten — Schlüsselmetriken',
    managerSec:'Dein lil.bet Manager',
    subSec:'Dein Sub-Netzwerk',
    metricsChanged:'✎ Metriken geändert',
    promoNone:'Keine Boni. GGR = NGR =',
    promoHas:'= NGR. RS wird von NGR berechnet.',
    promoGgr:'GGR', promoMinus:'− Boni', promoLabel:'Promo',
    perWeek:'/ Wo.',belowThreshold:'⚠ Unter $30 Schwelle',
    rsTimelineLabel:'RS wächst mit Spielerrückkehr',
    cpaTimelineLabel:'CPA — einmalige Zahlung, wächst nicht',
    hybridTimelineLabel:'Hybrid: einmal CPA + RS auf Rückkehr',
    firstDeposit:'Ersteinzahlung', perPlayer:'pro Spieler',
    cohortLabel:'Kohorte', avgFtdLabel:'Ersteinzahlung',
    ngr1mShort:'NGR / 1Mo', ngr6mShort:'NGR / 6Mo', ltv12mShort:'LTV / 12Mo',
    tierCurrentMark:'← aktuell', tierMaxed:'✓ Maximale Stufe erreicht',
    tierMoreFtd:'Noch', tierFtdWord:'FTD', tierAndRate:'diesen Monat — und Rate steigt auf',
    tierOnAll:'für den ganzen Monat',
    tierHowLabel:'Wie die Leiter funktioniert:',
    tierHowText:'Rate wird nach FTD-Anzahl <em>im aktuellen Monat</em> bestimmt und auf <em>alle FTD</em> dieses Monats angewendet.',
    tierMonthReset:'Nächsten Monat neu berechnet.',
    tierBringFtd:'Bringe', tierFtdRate:'FTD → Rate',
    rsSliderLabel:'RevShare % (vereinbart):',
    rsTierHigher:'📈 Volumen-Tier:', rsTierApplied:'— automatisch angewendet',
    rsTierLower:'Volumen-Tier:', rsTierApplied2:'Vereinbarte Rate angewendet',
    rsTierEqual:'Tier entspricht Rate:',
    rsSliderMin:'15% Start', rsSliderMid:'25–40% Haupt', rsSliderMax:'65% Top',
    cpaUnavail:'⛔ CPA nicht verfügbar für dieses GEO',
    cpaAskManager:'CPA-Rate für', cpaAskManager2:'beim Manager erfragen',
    cpaCustomLabel:'CPA-Rate, $',
    hybridOfficialPre:'Offizielles Hybridmodell:',hybridOfficialPerFtd:'/FTD einmalig +',hybridOfficialRs:'RS von NGR',
    hybridCpaPart:'CPA Teil', hybridRsPart:'RS Teil',
    hybridCpaOnce:'pro FTD (einmalig)', hybridRsMonthly:'von Spieler-NGR monatlich',
    hybridManualPre:'Manueller Hybrid: einmaliges CPA pro FTD + RS von NGR monatlich',
    hybridCpaLabel:'CPA pro FTD:', hybridRsLabel:'RS von NGR:',
    hybridCpaOnceNote:'CPA wird', hybridCpaOnceBold:'einmalig', hybridCpaOnceEnd:'bei FTD gezahlt.',
    hybridRsNote:'RS wird', hybridRsBold:'monatlich', hybridRsEnd:'gutgeschrieben, solange der Spieler aktiv ist.',
    holdDays:'Hold: 14 Tage', cpaAskNote:'Rate vom Manager. Hold: 14 Tage.',
    egyptWarn:'⚠️ Marken-Traffic', egyptWarn2:'für Ägypten: RS wird als 10% angewendet.',
    rsByYear:'RS an Partner / Jahr', cpaOncePay:'CPA an Partner (einmalig)', diffYear:'Unterschied pro Jahr',
    rsWins:'RS besser für das Jahr', cpaWins:'CPA zahlt mehr — Spieler bleiben nicht lange',
    cmpLegendRs:'RS % (kumuliert)', cmpLegendCpa:'CPA $ (einmalig)',
    beCross:'RS amortisiert CPA im Monat', beMonth:'', beAfter:'— danach bringt jeder Monat zusätzliches Einkommen.',
    beWarnPre:'⚠️ Bei aktuellen Parametern zahlt CPA mehr über 12 Monate. RS wird besser ab', beWarnOr:'% oder FTD ab',
    cmpPeriod:'Zeitraum', rsCumulHeader:'RS (kumuliert)', cpaHeader:'CPA (einmalig)', diffHeader:'Unterschied', ngrBrandHeader:'Brand NGR',
    cmpFootnote:'* RS aus kumuliertem NGR der Kohorte. CPA einmalig pro FTD.',
    rsArgPassive:'Passives Einkommen bei Rückkehr',
    rsArgPassiveDesc:'Spieler kam nach 3 Wochen zurück — CPA zahlt nichts, RS zahlt noch',
    rsArgPassiveEnd:'von seinem Verlust.',
    rsArgWhale:'Whale-Effekt',
    rsArgWhaleDesc:'Großer Spieler mit $500/Mo NGR bringt RS',
    rsArgWhaleEnd:'/Mo.',
    rsArgShave:'Kein Shave-Risiko', rsArgShaveDesc:'RS aus realem NGR — alles in Statistik sichtbar.',
    rsArgCumul:'Kumulativer Effekt',
    rsArgCumulDescPre:'Mit stabilem Traffic wächst die Spielerbasis. Im Monat 12,',
    rsArgCumulDescMid:'FTD/Mo ergeben ~', rsArgCumulEnd:'aktive Spieler.',
    rsArgCpa:'CPA besser kurzfristig', rsArgCpaDesc:'Für 1–3 Monate Arbeit ist CPA besser. RS entfaltet sich ab 6–12+ Monaten.',
    ftdNetLabel:'Netzwerk-FTD gesamt / Mo', myMonthLabel:'Dein Einkommen / Mo', myYearLabel:'Dein Einkommen / Jahr',
    partnersHeader:'Partner', ngrNetHeader:'Netzwerk-NGR / Mo',
    subTipsItems:[
      ['🎯','Qualität > Quantität','Ein Partner mit 200 FTD ist besser als zehn mit 20.'],
      ['📊','Zeig diesen Rechner','Partner sehen echte Zahlen — nicht Prozente, sondern Geld.'],
      ['🔗','Sub-Affiliate als Anker','Ein Partner, der sein Netzwerk durch dich aufbaut, geht nicht weg.'],
      ['📈','Ratenerhöhung als Anreiz','Biete RS-Erhöhung bei Skalierung: 25% → 30% → 35%.'],
    ],
    adBudgetLabel:'Werbebudget', partnerMonthLabel:'Partner-Einkommen / Mo',
    netProfitLabel:'Nettogewinn', roiLabel:'ROI',
    costPerFtdLabel:'Kosten pro FTD', paybackLabel:'Budget-Amortisation',
    profitable:'✅ Kampagne profitabel. Für jeden $1 Ausgaben — $', profitableEnd:'Einnahmen.',
    unprofitable:'⚠️ Verlust bei aktuellen Parametern.',
    moSuffix:'Mo', moSuffixGt:'> 24 Mo',
    rollingDescPre:'Sie bringen konstant', rollingDescMid:'FTD jeden Monat',
    rollingDescPost:'Spieler aus Vormonaten kehren zurück — RS-Einkommen', rollingDescGrow:'wächst jeden Monat',
    rollingDescEnd:' auch wenn Traffic gleich bleibt.',
    rollingLegendRsSuffix:'% / Mo (monatl. Einkommen)', rollingLegendCpaSuffix:'/ Mo (neue FTD × Rate)',
    rollMo1:'RS Monat 1', rollMo6:'RS Monat 6', rollMo12:'RS Monat 12',
    rollGrowth:'Wachstum ×', rollMo1Sub:'nur neue Spieler', rollMo6Sub:'6 Kohorten aktiv', rollMo12Sub:'12 Kohorten aktiv', rollGrowthSub:'Mo 1 → Mo 12',
    rollRs12:'RS gesamt 12 Mo', rollCpa12:'CPA gesamt 12 Mo',
    rollCrossPre:'📈 Ab Monat', rollCrossMid:'übersteigt RS CPA monatlich. Im Monat 12 bringt RS',
    rollCrossMonEnd:'/Mo —', rollCrossX:'× mehr als CPA für denselben Monat.',
    rollNoCross:'RS wächst, aber CPA bleibt monatlich besser. Versuchen Sie die RS-Rate zu erhöhen.',
    acceptSrcItems:[
      '✅ SEO / Content','✅ Telegram (Kanäle, Bots, Mini-Apps)','✅ Facebook / Instagram (PWA, APK)',
      '✅ Google UAC / ASO','✅ TikTok / Reels','✅ Influencer / Streamer',
      '✅ Push / Native','✅ Email / SMS','✅ Jede Arbitrage-Art',
      '✅ Jede Quelle mit echten Spielern',
    ],
    acceptSrcNote:'💬 Nicht-Standard-Quelle? Schreib dem Manager — wir finden eine Lösung.',
    restrictItems:[
      '⛔ Brand-PPC','⛔ Cookie-Stuffing','⛔ Spam-Versand',
      '⛔ Cloaking','⛔ Marken-Imitationsseiten',
      '⛔ Ägypten: Brand-Suche → RS 10%',
      '⛔ USA, UK, Frankreich, Spanien, Ukraine — gesperrt',
    ],
    competitorHeaders:['Programm','RS-Bereich','Admin-Fee','Neg. Saldo','Sub-Aff','Min. Zahlung','Cookie'],
    competitorNote:'Daten — öffentliche Bedingungen Mai 2026. Admin-Fee wird vor RS-Berechnung abgezogen.',
    scPeriod:'Zeitraum', scDiff:'Unterschied',
    scApproxEqual:'≈ gleich', scWinA:'▲ A +', scWinB:'▲ B +',
    scInsightWin:'Szenario', scInsightWinMid:'ist besser über 12 Mo um', scInsightWinEnd:'zeigt besten LTV.',
    scInsightEqual:'⚖️ Szenarien sind ungefähr gleich. Versuchen Sie GEO oder Modell zu ändern.',
    sc1mLabel:'1 Mo', sc3mLabel:'3 Mo', sc6mLabel:'6 Mo', sc12mLabel:'12 Mo', scMoSuffix:'1 Mo',
    payMin:'Min. Zahlung:', payFreq:'Häufigkeit:', payMethod:'Methode:', payHold:'Hold (CPA):',
    payMinVal:'$30', payFreqVal:'Wöchentlich (Dienstag)', payMethodVal:'Krypto (USDT, BTC, ETH)', payHoldVal:'14 Tage',
  },
  es:{
    headerSub:'/ calculadora de afiliados',
    tabCalc:'⚡ Calculadora', tabCompare:'📊 RS vs CPA', tabScenarios:'⚖️ Escenarios',
    tabSubaff:'🔗 Sub-afiliado', tabWhy:'✅ Por qué lil.bet',
    scAHeader:'Escenario A', scBHeader:'Escenario B', scDiffHeader:'Comparación de escenarios',
    earn1m:'1 mes', earn3m:'3 mes', earn6m:'6 mes', earn12m:'12 mes',
    partnerEarn:'Afiliado', brandNgr:'NGR marca',
    seasonNote:'⚠️ Estacionalidad no incluida — los valores reales pueden variar ±20–30%',
    tourSkip:'Saltar', tourNext:'Siguiente →', tourFinish:'¡Listo!',
    tourSteps:[
      {title:'👋 ¡Bienvenido!', text:'Esta calculadora muestra ganancias reales del programa de afiliados lil.bet.'},
      {title:'🌍 Paso 1 — Elige GEO', text:'Elige el país al que envías tráfico.'},
      {title:'📡 Paso 2 — Fuente de tráfico', text:'Elige de dónde vienen los jugadores.'},
      {title:'📊 Paso 3 — Modelo de pago', text:'RS, CPA o Hybrid.'},
      {title:'💰 Paso 4 — Tus ganancias', text:'¡Todo calculado! Cambia parámetros — resultados en tiempo real.'},
    ],
    uspItems:[
      ['0️⃣','0% Admin Fee','Pin-Up 20%, Vavada 14%. Nuestra tarifa: 0%.','#1'],
      ['🚫','Sin arrastre negativo','El mes malo no se arrastra.','USP'],
      ['🪙','$30 semanal cada martes','Umbral inferior a Mostbet ($50).','🔥'],
      ['🔗','Sub-afiliado 7%','Rango de mercado: 3–10%.'],
      ['🍪','Cookie 30 días Last Win','Vavada y Mostbet solo sesión.'],
      ['⚡','Manager directo','Sin tickets.'],
      ['📱','Telegram sin restricciones','Canales, bots, APK, PWA.'],
      ['🚀','Sin cap de FTD','Cualquier volumen de inmediato.'],
    ],
    geoSec:'GEO',
    trafficSec:'Volumen de tráfico',
    ftdLabel:'FTD por mes',
    clicksLabel:'Clics por mes',
    modeFtd:'Sé el FTD',
    modeClicks:'Sé los clics',
    roiToggle:'💰 Calculadora ROI (incluir costos)',
    srcSec:'Fuente de tráfico',
    modelSec:'Modelo de pago',
    ngrLabel:'NGR marca / mes',
    earnLabel:'Pago al afiliado / mes',
    timelineSec:'Ingresos de la cohorte',
    metricsSecLabel:'Métricas del jugador',
    tierSec:'Escalera RevShare',
    payoutSec:'Condiciones de pago',
    compareSec:'Ingresos de la cohorte por mes (acumulado)',
    compareIntro:'Cómo funciona la comparación: por cada FTD vía CPA el afiliado recibe un pago fijo de una vez. Vía RS — un porcentaje de cada pérdida del jugador.',
    rollingSec:'📈 Pronóstico de 12 meses — flujo constante de tráfico',
    whyUspSec:'Ventajas clave',
    whyPaySec:'Condiciones de pago — breve',
    whyAcceptSec:'Qué aceptamos',
    whyRestrictSec:'Restricciones',
    whyCompetitorSec:'lil.bet vs competidores — métricas clave',
    managerSec:'Tu manager en lil.bet',
    subSec:'Tu sub-red',
    metricsChanged:'✎ métricas editadas',
    promoNone:'Sin bonos. GGR = NGR =',
    promoHas:'= NGR. RS se calcula del NGR.',
    promoGgr:'GGR', promoMinus:'− bonos', promoLabel:'promo',
    perWeek:'/ sem.',belowThreshold:'⚠ Por debajo del umbral $30',
    rsTimelineLabel:'RS crece con el retorno de jugadores',
    cpaTimelineLabel:'CPA — pago único, no crece',
    hybridTimelineLabel:'Hybrid: CPA único + RS en retornos',
    firstDeposit:'primer depósito', perPlayer:'por jugador',
    cohortLabel:'cohorte', avgFtdLabel:'primer depósito',
    ngr1mShort:'NGR / 1mes', ngr6mShort:'NGR / 6mes', ltv12mShort:'LTV / 12mes',
    tierCurrentMark:'← actual', tierMaxed:'✓ Nivel máximo alcanzado',
    tierMoreFtd:'Más', tierFtdWord:'FTD', tierAndRate:'este mes — y la tasa sube a',
    tierOnAll:'para todo el mes',
    tierHowLabel:'Cómo funciona la escalera:',
    tierHowText:'La tasa se determina por FTD <em>en el mes actual</em> y se aplica a <em>todos los FTD</em> de ese mes.',
    tierMonthReset:'Se recalcula cada mes.',
    tierBringFtd:'Trae', tierFtdRate:'FTD → tasa',
    rsSliderLabel:'RevShare % (acordado):',
    rsTierHigher:'📈 Tier por volumen:', rsTierApplied:'— aplicado automáticamente',
    rsTierLower:'Tier por volumen:', rsTierApplied2:'Tasa acordada aplicada',
    rsTierEqual:'Tier coincide con tasa:',
    rsSliderMin:'15% inicio', rsSliderMid:'25–40% principal', rsSliderMax:'65% top',
    cpaUnavail:'⛔ CPA no disponible para este GEO',
    cpaAskManager:'Tasa CPA para', cpaAskManager2:'consultar al manager',
    cpaCustomLabel:'Tasa CPA, $',
    hybridOfficialPre:'Modelo híbrido oficial:',hybridOfficialPerFtd:'/FTD único +',hybridOfficialRs:'RS de NGR',
    hybridCpaPart:'Parte CPA', hybridRsPart:'Parte RS',
    hybridCpaOnce:'por FTD (único)', hybridRsMonthly:'de NGR del jugador mensualmente',
    hybridManualPre:'Híbrido manual: CPA único por FTD + RS de NGR mensual',
    hybridCpaLabel:'CPA por FTD:', hybridRsLabel:'RS de NGR:',
    hybridCpaOnceNote:'CPA se paga', hybridCpaOnceBold:'una vez', hybridCpaOnceEnd:'en FTD.',
    hybridRsNote:'RS se acumula', hybridRsBold:'mensualmente', hybridRsEnd:'mientras el jugador esté activo.',
    holdDays:'Hold: 14 días', cpaAskNote:'Tasa por el manager. Hold: 14 días.',
    egyptWarn:'⚠️ Tráfico de marca', egyptWarn2:'para Egipto: RS aplicado como 10%.',
    rsByYear:'RS al afiliado / año', cpaOncePay:'CPA al afiliado (único)', diffYear:'Diferencia por año',
    rsWins:'RS mejor por el año', cpaWins:'CPA paga más — jugadores no se quedan',
    cmpLegendRs:'RS % (acumulado)', cmpLegendCpa:'CPA $ (único)',
    beCross:'RS recupera CPA en el mes', beMonth:'', beAfter:'— después cada mes trae ingresos adicionales.',
    beWarnPre:'⚠️ Con parámetros actuales CPA paga más en 12 meses. RS supera con tasa superior a', beWarnOr:'% o FTD desde',
    cmpPeriod:'Período', rsCumulHeader:'RS (acumulado)', cpaHeader:'CPA (único)', diffHeader:'Diferencia', ngrBrandHeader:'NGR marca',
    cmpFootnote:'* RS del NGR acumulado de la cohorte. CPA pagado una vez por FTD.',
    rsArgPassive:'Ingreso pasivo en cada retorno',
    rsArgPassiveDesc:'El jugador regresó y perdió de nuevo — CPA no paga nada, RS paga otro',
    rsArgPassiveEnd:'de su pérdida.',
    rsArgWhale:'Efecto ballena',
    rsArgWhaleDesc:'Jugador de alto valor con NGR $500/mes da RS',
    rsArgWhaleEnd:'/mes.',
    rsArgShave:'Sin riesgo de shave', rsArgShaveDesc:'RS del NGR real — todo visible en estadísticas.',
    rsArgCumul:'Efecto acumulativo',
    rsArgCumulDescPre:'Con tráfico estable la base crece. En el mes 12,',
    rsArgCumulDescMid:'FTD/mes crean ~', rsArgCumulEnd:'jugadores activos.',
    rsArgCpa:'CPA mejor a corto plazo', rsArgCpaDesc:'Para 1–3 meses CPA es mejor. RS se despliega en 6–12+ meses.',
    ftdNetLabel:'FTD red total / mes', myMonthLabel:'Tu ingreso / mes', myYearLabel:'Tu ingreso / año',
    partnersHeader:'Afiliados', ngrNetHeader:'NGR red / mes',
    subTipsItems:[
      ['🎯','Calidad > cantidad','Un afiliado con 200 FTD vale más que diez con 20.'],
      ['📊','Muestra esta calculadora','El afiliado ve cifras reales — no porcentajes, sino dinero.'],
      ['🔗','Sub-afiliado como ancla','Un afiliado que construye su red a través de ti no se irá.'],
      ['📈','Aumento de tasa como incentivo','Ofrece subidas de RS: 25% → 30% → 35%.'],
    ],
    adBudgetLabel:'Presupuesto publicitario', partnerMonthLabel:'Ingreso afiliado / mes',
    netProfitLabel:'Beneficio neto', roiLabel:'ROI',
    costPerFtdLabel:'Costo por FTD', paybackLabel:'Amortización del presupuesto',
    profitable:'✅ Campaña rentable. Por cada $1 gastado — $', profitableEnd:'de ingresos.',
    unprofitable:'⚠️ Pérdida con parámetros actuales.',
    moSuffix:'mes', moSuffixGt:'> 24 mes',
    rollingDescPre:'Traes constantemente', rollingDescMid:'FTD cada mes',
    rollingDescPost:'Los jugadores de meses anteriores regresan — el ingreso RS', rollingDescGrow:'crece cada mes',
    rollingDescEnd:' incluso si el tráfico no cambia.',
    rollingLegendRsSuffix:'% / mes (ingreso mensual)', rollingLegendCpaSuffix:'/ mes (nuevos FTD × tasa)',
    rollMo1:'RS mes 1', rollMo6:'RS mes 6', rollMo12:'RS mes 12',
    rollGrowth:'Crecimiento ×', rollMo1Sub:'solo nuevos jugadores', rollMo6Sub:'6 cohortes activas', rollMo12Sub:'12 cohortes activas', rollGrowthSub:'mes 1 → mes 12',
    rollRs12:'RS total 12 mes', rollCpa12:'CPA total 12 mes',
    rollCrossPre:'📈 Desde el mes', rollCrossMid:'el RS mensual supera CPA. En mes 12 RS trae',
    rollCrossMonEnd:'/mes —', rollCrossX:'× más que CPA ese mes.',
    rollNoCross:'RS crece, pero CPA sigue siendo mayor mensualmente. Prueba subir la tasa RS.',
    acceptSrcItems:[
      '✅ SEO / Contenido','✅ Telegram (canales, bots, mini-apps)','✅ Facebook / Instagram (PWA, APK)',
      '✅ Google UAC / ASO','✅ TikTok / Reels','✅ Influencers / Streamers',
      '✅ Push / Native','✅ Email / SMS','✅ Cualquier tipo de arbitraje',
      '✅ Cualquier fuente de jugadores reales',
    ],
    acceptSrcNote:'💬 ¿Fuente no estándar? Escribe al manager — encontraremos solución.',
    restrictItems:[
      '⛔ PPC de marca','⛔ Cookie stuffing','⛔ Spam',
      '⛔ Cloaking','⛔ Sitios de imitación de marca',
      '⛔ Egipto: búsqueda de marca → RS 10%',
      '⛔ USA, UK, Francia, España, Ucrania — bloqueado',
    ],
    competitorHeaders:['Programa','Rango RS','Admin fee','Saldo negativo','Sub-af','Min. pago','Cookie'],
    competitorNote:'Datos — condiciones públicas mayo 2026. Admin fee se deduce del NGR antes del RS.',
    scPeriod:'Período', scDiff:'Diferencia',
    scApproxEqual:'≈ igual', scWinA:'▲ A +', scWinB:'▲ B +',
    scInsightWin:'Escenario', scInsightWinMid:'es mejor en 12 mes por', scInsightWinEnd:'muestra mejor LTV.',
    scInsightEqual:'⚖️ Escenarios son aproximadamente iguales. Prueba cambiar GEO o modelo.',
    sc1mLabel:'1 mes', sc3mLabel:'3 mes', sc6mLabel:'6 mes', sc12mLabel:'12 mes', scMoSuffix:'1 mes',
    payMin:'Pago mín.:', payFreq:'Frecuencia:', payMethod:'Método:', payHold:'Hold (CPA):',
    payMinVal:'$30', payFreqVal:'Semanal (martes)', payMethodVal:'Crypto (USDT, BTC, ETH)', payHoldVal:'14 días',
  },
};

function t(key){ return (LANG[currentLang]||LANG.en)[key] || (LANG.en)[key] || key; }

function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    var val = t(key);
    if (val && val !== key) el.textContent = val;
  });
}

function switchLang(lang){
  currentLang = lang;
  localStorage.setItem('calc_lang', lang);
  // Update lang buttons
  document.querySelectorAll('.lang-btn').forEach(function(b) { b.classList.remove('active'); });
  document.querySelectorAll('.lang-btn').forEach(function(b) {
    if(b.textContent.toLowerCase()===lang||b.textContent.toUpperCase()===lang.toUpperCase()) b.classList.add('active');
  });
  // Apply data-i18n translations
  applyI18n();
  // Update static elements (keep for backward compat)
  var L = LANG[lang] || LANG.en;
  document.getElementById('headerSub').textContent = L.headerSub;
  ['calc','compare','scenarios','subaff','why'].forEach(function(id) {
    var el = document.getElementById('tab-'+id);
    if(el) el.textContent = L['tab'+id.charAt(0).toUpperCase()+id.slice(1)] || el.textContent;
  });
  // Update tour buttons if tour open
  var skipBtn = document.getElementById('tourSkipBtn');
  var nextBtn = document.getElementById('tourNextBtn');
  if(skipBtn) skipBtn.textContent = L.tourSkip;
  if(nextBtn) nextBtn.textContent = tourStep >= (L.tourSteps.length-1) ? L.tourFinish : L.tourNext;
  // Update scenario headers
  var sh = {scAHeader:'scAHeader', scBHeader:'scBHeader', scDiffHeader:'scDiffHeader'};
  Object.entries(sh).forEach(function(entry) { var k=entry[0],id=entry[1]; var e=document.getElementById(id); if(e) e.textContent=L[k]; });
  renderAll();
  renderWhy();
  renderScenarios();
}
